### PR TITLE
Simplify dukeds backend

### PR DESCRIPTION
**Pull request by johnbradley**
Moves utility methods from .backends.dukeds.py to .oauth_utils.py
This removes a dependency where `gcb_web_auth/oauth_utils.py` depended upon `gcb_web_auth/backends/dukeds.py`. This caused import issues when used in bespin-api.

### CODE REVIEW

**Comment by dleehr** [comment]
I meant to comment on this earlier - This change puts DukeDS-specific code into`oauth_utils.py`, which it deliberately did not have. I don't fully understand the rationale for the move, but if these functions need to be moved out of the backend, perhaps they belong in something like `duked_utils.py`?

**Comment by dleehr** [comment]
Actually scratch that. I'm confusing myself. oauth_utils already has dukeds stuff in it.

**Comment by johnbradley** [comment]
The issue I am trying to fix is an import failing when this backend was imported.
Depending on what has already been imported it will import fine or fail.

**Comment by dleehr** [comment]
How about if we rename `oauth_utils.py` to just `utils.py`, since it's basically just a bunch of utility functions. That way I won't confuse myself.

**Pull request merged**
